[33mWARNING [0m urllib3.connectionpool:connectionpool.py:813 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f630e002910>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/c31608f3-5d04-42af-b759-88ceade94cb4
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:813 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f630e00ec10>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/c31608f3-5d04-42af-b759-88ceade94cb4
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:813 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f630e01a950>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/c31608f3-5d04-42af-b759-88ceade94cb4