[33mWARNING [0m urllib3.connectionpool:connectionpool.py:813 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f630dfe2c50>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/a3b17be9-887f-4b90-a0a1-81c678c14c1e
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:813 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f630e002e90>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/a3b17be9-887f-4b90-a0a1-81c678c14c1e
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:813 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f630e002690>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/a3b17be9-887f-4b90-a0a1-81c678c14c1e