{"uuid": "9d7b8834-69ff-4496-b969-4717db2eaf33", "children": ["aad04f68-6d9e-4566-8ac9-c3fed4dd9132"], "befores": [{"name": "new_user", "status": "passed", "steps": [{"name": "Генерация фейковых кредов для регистрации пользователя", "status": "passed", "start": 1716385301473, "stop": 1716385301496}, {"name": "Регистрация нового пользователя", "status": "passed", "parameters": [{"name": "user_data", "value": "{'email': 'luka_22@example.net', 'password': ')1bPKrtjVb', 'name': 'alevtina74'}"}], "start": 1716385301496, "stop": 1716385302073}], "start": 1716385301473, "stop": 1716385302073}], "afters": [{"name": "new_user::0", "status": "broken", "statusDetails": {"message": "KeyboardInterrupt\n", "trace": "  File \"/usr/local/lib/python3.11/dist-packages/allure_commons/_allure.py\", line 221, in __call__\n    return self._fixture_function(*args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/usr/lib/python3/dist-packages/_pytest/fixtures.py\", line 917, in _teardown_yield_fixture\n    next(it)\n  File \"/home/user/yandex/Diplom3/conftest.py\", line 36, in new_user\n    User.delete_user(new_user_response.json()[\"accessToken\"])\n  File \"/usr/local/lib/python3.11/dist-packages/allure_commons/_allure.py\", line 192, in impl\n    return func(*a, **kw)\n           ^^^^^^^^^^^^^^\n  File \"/home/user/yandex/Diplom3/helps.py\", line 36, in delete_user\n    response = requests.delete(EndPoints.login_user, headers=headers)\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/usr/lib/python3/dist-packages/requests/api.py\", line 157, in delete\n    return request(\"delete\", url, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/usr/lib/python3/dist-packages/requests/api.py\", line 59, in request\n    return session.request(method=method, url=url, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/usr/lib/python3/dist-packages/requests/sessions.py\", line 587, in request\n    resp = self.send(prep, **send_kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/usr/lib/python3/dist-packages/requests/sessions.py\", line 701, in send\n    r = adapter.send(request, **kwargs)\n        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/usr/lib/python3/dist-packages/requests/adapters.py\", line 489, in send\n    resp = conn.urlopen(\n           ^^^^^^^^^^^^^\n  File \"/usr/lib/python3/dist-packages/urllib3/connectionpool.py\", line 704, in urlopen\n    httplib_response = self._make_request(\n                       ^^^^^^^^^^^^^^^^^^^\n  File \"/usr/lib/python3/dist-packages/urllib3/connectionpool.py\", line 387, in _make_request\n    self._validate_conn(conn)\n  File \"/usr/lib/python3/dist-packages/urllib3/connectionpool.py\", line 1045, in _validate_conn\n    conn.connect()\n  File \"/usr/lib/python3/dist-packages/urllib3/connection.py\", line 358, in connect\n    self.sock = conn = self._new_conn()\n                       ^^^^^^^^^^^^^^^^\n  File \"/usr/lib/python3/dist-packages/urllib3/connection.py\", line 187, in _new_conn\n    self, \"Failed to establish a new connection: %s\" % e\n          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~\n"}, "steps": [{"name": "Удаление пользователя", "status": "broken", "statusDetails": {"message": "KeyboardInterrupt\n", "trace": "  File \"/usr/local/lib/python3.11/dist-packages/allure_commons/_allure.py\", line 192, in impl\n    return func(*a, **kw)\n           ^^^^^^^^^^^^^^\n  File \"/home/user/yandex/Diplom3/helps.py\", line 36, in delete_user\n    response = requests.delete(EndPoints.login_user, headers=headers)\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/usr/lib/python3/dist-packages/requests/api.py\", line 157, in delete\n    return request(\"delete\", url, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/usr/lib/python3/dist-packages/requests/api.py\", line 59, in request\n    return session.request(method=method, url=url, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/usr/lib/python3/dist-packages/requests/sessions.py\", line 587, in request\n    resp = self.send(prep, **send_kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/usr/lib/python3/dist-packages/requests/sessions.py\", line 701, in send\n    r = adapter.send(request, **kwargs)\n        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/usr/lib/python3/dist-packages/requests/adapters.py\", line 489, in send\n    resp = conn.urlopen(\n           ^^^^^^^^^^^^^\n  File \"/usr/lib/python3/dist-packages/urllib3/connectionpool.py\", line 704, in urlopen\n    httplib_response = self._make_request(\n                       ^^^^^^^^^^^^^^^^^^^\n  File \"/usr/lib/python3/dist-packages/urllib3/connectionpool.py\", line 387, in _make_request\n    self._validate_conn(conn)\n  File \"/usr/lib/python3/dist-packages/urllib3/connectionpool.py\", line 1045, in _validate_conn\n    conn.connect()\n  File \"/usr/lib/python3/dist-packages/urllib3/connection.py\", line 358, in connect\n    self.sock = conn = self._new_conn()\n                       ^^^^^^^^^^^^^^^^\n  File \"/usr/lib/python3/dist-packages/urllib3/connection.py\", line 187, in _new_conn\n    self, \"Failed to establish a new connection: %s\" % e\n          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~\n"}, "parameters": [{"name": "user_token", "value": "'Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY2NGRmNjE1OWVkMjgwMDAxYjQxNzYwZCIsImlhdCI6MTcxNjM4NTMwMSwiZXhwIjoxNzE2Mzg2NTAxfQ.iYJasNHCljWMsN4ZlXJSfMR4FUkUBN05Y0fR502b3XE'"}], "start": 1716385428869, "stop": 1716385442703}], "start": 1716385428869, "stop": 1716385442722}], "start": 1716385301473, "stop": 1716385442722}