[33mWARNING [0m urllib3.connectionpool:connectionpool.py:813 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f630dfd6c10>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/04a3a9b1-9a9b-4d22-9e0f-504593ec6850
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:813 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f630dfe2e10>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/04a3a9b1-9a9b-4d22-9e0f-504593ec6850
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:813 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f630e002b10>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/04a3a9b1-9a9b-4d22-9e0f-504593ec6850