[33mWARNING [0m urllib3.connectionpool:connectionpool.py:813 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f630dfe4d90>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/1e51499c-9b02-4abe-84a7-a5120f1e74d8
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:813 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f630dfe0a10>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/1e51499c-9b02-4abe-84a7-a5120f1e74d8
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:813 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f630dfe1d10>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/1e51499c-9b02-4abe-84a7-a5120f1e74d8