[33mWARNING [0m urllib3.connectionpool:connectionpool.py:813 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f630e052510>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/4d9f6091-2fe8-421c-abdf-5bf9aeab3063
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:813 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f630e0f1c50>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/4d9f6091-2fe8-421c-abdf-5bf9aeab3063
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:813 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f630dfe0110>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/4d9f6091-2fe8-421c-abdf-5bf9aeab3063