[33mWARNING [0m urllib3.connectionpool:connectionpool.py:813 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f630e0091d0>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/da6b688b-c8fd-49e9-9737-ba4625cc2f43
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:813 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f630dfe1050>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/da6b688b-c8fd-49e9-9737-ba4625cc2f43
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:813 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f630dfe2110>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/da6b688b-c8fd-49e9-9737-ba4625cc2f43