[33mWARNING [0m urllib3.connectionpool:connectionpool.py:813 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f630dfd7050>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/1893b7be-d031-4bb1-9f50-664b36772d02
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:813 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f630e052d90>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/1893b7be-d031-4bb1-9f50-664b36772d02
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:813 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f630e053310>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/1893b7be-d031-4bb1-9f50-664b36772d02