[33mWARNING [0m urllib3.connectionpool:connectionpool.py:813 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f630e1ab310>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/72c15548-dfdd-427d-92fc-ade04f4f34df
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:813 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f630e02dc90>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/72c15548-dfdd-427d-92fc-ade04f4f34df
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:813 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f630e02da10>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/72c15548-dfdd-427d-92fc-ade04f4f34df